### ISSUE TITLE
Getting syntax error, unexpected on line 125

### ISSUE THREAD

**Issue by burhan93** [kadimi/remove-fields#1]
Hello. 

Can  you please help me solve this issue in your plugin, it was working perfectly on my old server but when  I transferred the site to the new server, it generated this error.

Parse error: syntax error, unexpected '[' in /home/content/52/10010552/html/site/wp-content/plugins/remove-fields/remove-fields.php on line 125

Awaiting your response.

Thanks in advance.

**Comment by kadimi** [comment]
Hi,

Please update your PHP version, [the current supported version of PHP are 5.6 and 7.0](http://php.net/supported-versions.php) but the plugin will work with 5.4 and 5.5 as well.
